# Generated by Django 6.0.3 on 2026-03-18 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(help_text='Supabase Auth ID')),
                ('nombre_local', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('descripcion_corta', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_celular', models.CharField(blank=True, max_length=50, null=True)),
                ('redes_sociales', models.JSONField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('popularidad', models.PositiveIntegerField(default=0)),
                ('estado_aprobacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_local',
            },
        ),
        migrations.CreateModel(
            name='ComentarioLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(help_text='Supabase Auth ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('visible', 'Visible'), ('oculto', 'Oculto')], default='visible', max_length=10)),
                ('contador_likes', models.PositiveIntegerField(default=0)),
                ('comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='locales.comentariolocal')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='locales.local')),
            ],
            options={
                'db_table': 'core_comentariolocal',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('popularidad', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='locales.local')),
            ],
            options={
                'db_table': 'core_menu',
                'ordering': ['-popularidad', '-fecha_creacion'],
            },
        ),
    ]
