# Generated by Django 5.2.7 on 2025-11-16 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comentarioreceta_comentario_padre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(help_text="Comentario al que se le dio 'Me Gusta'.", on_delete=django.db.models.deletion.CASCADE, related_name='likes_recibidos', to='core.comentarioreceta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_dados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Me Gusta del Comentario',
                'verbose_name_plural': 'Me Gustas de los Comentarios',
                'unique_together': {('usuario', 'comentario')},
            },
        ),
    ]
