# Generated by Django 6.0.3 on 2026-03-18 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(blank=True, help_text='Supabase Auth ID', null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion_corta', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_larga', models.TextField(blank=True, null=True)),
                ('preparacion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('dificultad', models.CharField(choices=[('Muy Fácil', 'Muy Fácil'), ('Fácil', 'Fácil'), ('Media', 'Media'), ('Difícil', 'Difícil'), ('Muy Difícil', 'Muy Difícil')], default='Media', max_length=15)),
                ('numero_porcion', models.PositiveIntegerField(default=1)),
                ('ingredientes', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contador_likes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'core_receta',
            },
        ),
        migrations.CreateModel(
            name='ComentarioReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(help_text='Supabase Auth ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('visible', 'Visible'), ('oculto', 'Oculto')], default='visible', max_length=10)),
                ('contador_likes', models.PositiveIntegerField(default=0)),
                ('comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='recetas.comentarioreceta')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='recetas.receta')),
            ],
            options={
                'db_table': 'core_comentarioreceta',
            },
        ),
        migrations.CreateModel(
            name='ComentarioLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(help_text='Supabase Auth ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(help_text="Comentario al que se le dio 'Me Gusta'.", on_delete=django.db.models.deletion.CASCADE, related_name='likes_recibidos', to='recetas.comentarioreceta')),
            ],
            options={
                'verbose_name': 'Me Gusta del Comentario',
                'verbose_name_plural': 'Me Gustas de los Comentarios',
                'db_table': 'core_comentariolike',
                'unique_together': {('user_id', 'comentario')},
            },
        ),
        migrations.CreateModel(
            name='RecetaGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(help_text='Supabase Auth ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta')),
            ],
            options={
                'db_table': 'core_recetaguardada',
                'unique_together': {('user_id', 'receta')},
            },
        ),
        migrations.CreateModel(
            name='RecetaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(help_text='Supabase Auth ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta')),
            ],
            options={
                'db_table': 'core_recetalike',
                'unique_together': {('user_id', 'receta')},
            },
        ),
    ]
