# Generated by Django 6.0.3 on 2026-03-19 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('calorias_por_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('proteinas_por_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carbohidratos_por_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('grasas_por_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fibra_por_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('azucares_por_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sodio_mg_por_100g', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('peso_por_unidad_gramos', models.DecimalField(blank=True, decimal_places=2, help_text="Usado si se vende o cuenta por 'unidad' (ej: 1 huevo = 50g)", max_digits=8, null=True)),
            ],
            options={
                'db_table': 'core_ingrediente',
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='total_calorias',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='receta',
            name='total_carbohidratos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='receta',
            name='total_grasas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='receta',
            name='total_proteinas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unidad', models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros'), ('unidad', 'Unidades'), ('taza', 'Tazas'), ('cda', 'Cucharadas'), ('cdta', 'Cucharaditas')], default='g', max_length=50)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_detalle', to='recetas.receta')),
            ],
            options={
                'db_table': 'core_recetaingrediente',
            },
        ),
    ]
