# Generated by Django 6.0.3 on 2026-03-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_ingrediente_receta_total_calorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='categoria',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='es_libre_de_gluten',
            field=models.BooleanField(default=False, verbose_name='Es Libre de Gluten'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='es_vegano',
            field=models.BooleanField(default=False, verbose_name='Es Vegano'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='peso_por_cucharada_gramos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso por cucharada (g)'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='peso_por_taza_gramos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso por taza (g)'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='azucares_por_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Azúcares/100g'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='calorias_por_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Calorías/100g'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='carbohidratos_por_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Carbohidratos/100g'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='fibra_por_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fibra/100g'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='grasas_por_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Grasas/100g'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='peso_por_unidad_gramos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Usado si se vende o cuenta por 'unidad' (ej: 1 huevo = 50g)", max_digits=10, null=True, verbose_name='Peso por unidad típica (g)'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='proteinas_por_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Proteínas/100g'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='sodio_mg_por_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sodio (mg)/100g'),
        ),
    ]
