# Generated by Django 6.0.3 on 2026-03-20 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_ingrediente_categoria_ingrediente_es_libre_de_gluten_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'core_estilovida',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'core_pais',
            },
        ),
        migrations.CreateModel(
            name='TipoPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'core_tipoplato',
            },
        ),
        migrations.RemoveField(
            model_name='receta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='receta',
            name='sugerencias',
            field=models.TextField(blank=True, help_text='Tips o sugerencias del chef', null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo de preparación en minutos', null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='estilos_vida',
            field=models.ManyToManyField(blank=True, related_name='recetas', to='recetas.estilovida'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='recetas.pais'),
        ),
        migrations.AddField(
            model_name='receta',
            name='tipo_plato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='recetas.tipoplato'),
        ),
    ]
