# Generated by Django 6.0.3 on 2026-03-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(help_text='Supabase Auth ID', unique=True)),
                ('razon', models.TextField(help_text='Razón del baneo')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha en la que expira el baneo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_banneduser',
            },
        ),
    ]
